#TESTS=basic mini diff pyr rects foltok
ALLTESTS=basic mini diff pyr rects foltok delt deshake
TESTS=deshake
# TESTS=foltok
TEMPS=smiley.raw smiley2.bmp

FFMPEG=ffmpeg
FFPLAY=ffplay

IN=shk.mkv
OUT=nshk.mkv
WIDTH=1280
HEIGHT=720
# WIDTH=1920
# HEIGHT=1080
OWIDTH=1280
OHEIGHT=720
FPIX=rgb24
VPIX=rgb24

# FPIX=gray8
# VPIX=g8

LIBS=vulcmp vultools vulimg
INCDIR=$(LIBS:%=../../%)
LIBDIR=$(INCDIR)

RM=rm -f
CC=gcc -g
SPACE=$(eval) $(eval)

CFL=$(INCDIR:%=-I%) $(LIBDIR:%=-L%)
LFL=$(LIBS:%=-l%)
RFL=LD_LIBRARY_PATH=$(subst $(SPACE),:,$(LIBDIR))

test: $(TESTS:=.run)

clean:
	$(RM) $(ALLTESTS:=.elf) $(TEMPS)

mini.elf: mini.c
	$(CC) $(CFL) -o $@ $^ $(LFL)

basic.elf: basic.c
	$(CC) $(CFL) -o $@ $^ $(LFL)

foltok.elf: foltok.c
	$(CC) $(CFL) -o $@ $^ $(LFL)

diff.elf: diff.c frameproc.c
	$(CC) $(CFL) -o $@ $^ $(LFL)

diff.run: diff.elf
	$(FFMPEG) -i $(IN) -pix_fmt $(FPIX) -c:v rawvideo -f rawvideo - \
        | $(RFL) ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX) \
        | $(FFPLAY) - -f rawvideo -video_size $(WIDTH)x$(HEIGHT) -pixel_format $(FPIX)

rects.elf: rects.c frameproc.c
	$(CC) $(CFL) -o $@ $^ $(LFL)

rects.run: rects.elf
	$(FFMPEG) -i $(IN) -pix_fmt $(FPIX) -c:v rawvideo -f rawvideo - \
        | $(RFL) ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX) \
	| $(FFPLAY) - -f rawvideo -video_size $(WIDTH)x$(HEIGHT) -pixel_format $(FPIX)

#        | $(RFL) valgrind --tool=callgrind ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX) \
#        | $(RFL) ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX) \

deshake.elf: deshake.c frameproc.c
	$(CC) $(CFL) -o $@ $^ $(LFL)

deshake.run: deshake.elf
	$(FFMPEG) -i $(IN) -pix_fmt $(FPIX) -c:v rawvideo -f rawvideo - \
	| $(RFL) ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX) -n 10 \
	| $(FFPLAY) - -f rawvideo -video_size $(WIDTH)x$(HEIGHT) -pixel_format $(FPIX)



#	| $(FFPLAY) - -f rawvideo -video_size $(WIDTH)x$(HEIGHT) -pixel_format $(FPIX)
#	| $(FFMPEG) -f rawvideo -pix_fmt $(FPIX) -s $(WIDTH)x$(HEIGHT) -i - -c:v libx264 $(OUT)



delt.elf: delt.c
	$(CC) $(CFL) -o $@ $^ $(LFL)

delt.run: delt.elf
	$(RFL) ./$<

#	| $(RFL) ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX) -n 10 \

#	cat shk.raw \

#	$(FFMPEG) -i $(IN) -pix_fmt $(FPIX) -c:v rawvideo -f rawvideo - \
#       | $(RFL) ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX)\
#	| $(FFPLAY) - -f rawvideo -video_size $(OWIDTH)x$(OHEIGHT) -pixel_format $(FPIX)

pyr.elf: pyr.c frameproc.c
	$(CC) $(CFL) -o $@ $^ $(LFL)

pyr.run: pyr.elf
	$(FFMPEG) -i $(IN) -pix_fmt $(FPIX) -c:v rawvideo -f rawvideo - \
        | $(RFL) ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX)\
	| $(FFPLAY) - -f rawvideo -video_size $(OWIDTH)x$(OHEIGHT) -pixel_format $(FPIX)

#        | $(RFL) valgrind --tool=callgrind ./$< -w $(WIDTH) -h $(HEIGHT) -p $(VPIX)
#	| cat > /dev/null
#	| cat > /dev/null
#	> out.raw

%.run: %.elf
	$(RFL) ./$<

.PHONY: %.run
