include Makefile.defs

DIRS=$(VULCMPDIR) $(VYTOOLSDIR) .

GLSLIS=copy1 copy32 join3 plane3 trans diff dsum add8
GLSLPS=pyr delta8
GLSLDS=rect fill
GLSLWS=white8 wcloud8

GLSLS=$(GLSLSIS) $(GLSLWS) $(GLSPS) $(GLSLSDS)

CC=gcc -g $(DIRS:%=-L%) $(DIRS:%=-I%)
CPP=g++ -g $(DIRS:%=-L%) $(DIRS:%=-I%)
GLSLC=glslc
RM=rm -f
EH=@echo
XXD=xxd

MLIN=make -f Makefile.linux
MDEB=make
LIB=lib$(NAME).so
PLIB=lib$(NAME)p.so
	
build: $(LIB) $(PLIB)

clean:
	$(RM) $(LIB) *.o *.inc *.spv
	cd test && $(MLIN) clean
	cd debian && $(MDEB) clean

test: build
	cd test && $(MLIN)

debian: build
	cd debian && $(MDEB)

help:
	$(EH) ''
	$(EH) 'Make targets:'
	$(EH) '   build: build library'
	$(EH) '   clean: clean directory'
	$(EH) '   test: run tests'
	$(EH) '   debian: build debian package (.deb)'
	$(EH) ''

%.inc: %.spv
	$(XXD) -i $< > $@

%.spv: %.glsl vulimg_comp.h
	$(GLSLC) -o $@ $<

vulimg.o: vulimg.c vulimg_impl.h vulimg.h $(GLSLIS:=.inc)
	$(CC) -c -fPIC -Wall -o $@ $<

vulimgp.o: vulimgp.cpp vulimg.hpp
	$(CPP) -c -fPIC -Wall -o $@ $<

draw.o: draw.c vulimg_impl.h vulimg.h $(GLSLDS:=.inc)
	$(CC) -c -fPIC -Wall -o $@ $<

pyr.o: pyr.c vulimg_impl.h vulimg.h $(GLSLPS:=.inc)
	$(CC) -c -fPIC -Wall -o $@ $<

white.o: white.c vulimg_impl.h vulimg.h $(GLSLWS:=.inc)
	$(CC) -c -fPIC -Wall -o $@ $<

$(LIB): vulimg.o draw.o white.o pyr.o
	$(CC) -shared -o $@ $^ -lvulcmp -lvytools

$(PLIB): vulimgp.o 
	$(CPP) -shared -o $@ $^ -lvulcmp -lvulimg

.PHONY: test

head:
	$(MAKE) 2>&1 | head -n 20
